# Identity Provider.
idp:
  verify_host_name: true

# SAML MetaData feed with all allowed SPs. Can (and should) be a https resource
serviceproviders:
#  feed: https://engine.test2.surfconext.nl/authentication/sp/metadata
  feed: classpath:saml/eb.sp.test.metadata.saml.xml
  allow_unknown: false
