# The logging configuration. On a real server this will be a file url. e.g. file://{{ eidas_dir }}/logback.xml
logging:
  config: classpath:logback.xml
  level:
    ps: DEBUG
    org.springframework.security: DEBUG

server:
  # The port to where this Spring Boot application listens to. e.g. http://localhost:{{ springapp_tcpport }}
  port: 8080
  # The context path of the server. You can skip this value in the overriding application.yml on the classpath
  contextPath:
  session:
    cookie:
      secure: false

# Identity Provider.
idp:
  verify_host_name: true

# SAML MetaData feed with all allowed SPs. Can (and should) be a https resource
serviceproviders:
#  feed: https://engine.test2.surfconext.nl/authentication/sp/metadata
  feed: classpath:saml/eb.sp.metadata.xml
  allow_unknown: false

# eidas
proxy:
  # base url
  base_url: http://localhost:8080
  # Entity ID of the SP
  entity_id: https://eidas.localhost.surfconext.nl
  # Private key used to sign the SAML response
  private_key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC7zmyB3sTqGGTwuokkh75pQFVTqBYoYFsXPVqPl0299OqhNYpErfKnYYypyo3AMCxJJxZKLGwdF0JjeegyC9BbwTeXkwSOhRc39QRyIHuDsUkrq6imcKRQjMqn90JRXm6o1PMHz807CHL2zCCzgfvtgcBpeUDZ4+ba9q5/RAwsAl/KL3STdgbWyT16TIxOBzFStEt9QpAOfPiLwj39225WP7m/v/BJHV8MHwHGBg1WYX+H/ah5NSWJMSj/0XSoG+lriS9HObPpFP/BrfwTemvrxqbz7lvHozcVT6bJx+alz4IWYYU0ptMZEG2LCQjDK1rnkcY7EbiUqKQhe+l4S7TnAgMBAAECggEARHUlRl2+p5pGyR0luoQkm1cRA1KE6Sjea2U46ph7hR+Omz7Z7Nj/V5YOYSHtc73blrrBvD3fFueQkpQwWHXH+HpA2maDxbOr2ADfIv7GJyXrhximfC0ZKCd6A6n0qZZjffVJtXJA3CDjTyTvUp+yBkxCp+/D/Oi/ENfUmZ1jVnLS71pGPNemptRZWTkz/q6rm2bv8tQvCiRqGzta4iBVyCxo26j5cCzKKUd6qLCrsl3mcL+4JulKq5CRs9hTZN+obwOygnC6WBz557tbg6xafq7SEqlFu7w2KUd+dAcHXvPcYwgYKlYjPmaKu0ERzmCJYpxvzeTB4c53nt3Bq72XcQKBgQDpab6ZLjdEbIyHHGsCdl0zq/T2L8GaI/XpyOlJ916CuAmKq/bxtMxr8ChfPCI9vNS9Qmqli0hnR+dMLvQM25iRHYhnwN5AQluK8lW9JkU2seGVSGxAUQfK5lB192FoerIijzHELe5r+9x1YxEICSNqGj/l716jJuVnlG73ucxdiQKBgQDN+uGCqfK2Nvs+uX+1KJ416Skm9+Exmh5r9sX7+LyY4h5MDaAGdwP+KCxNbbPiQaCjuTuZqDi/Rk0Yk2ruoNrGfhMb951Q5nYNDvxPAuYezrJtPuVCpEp+pzGaS89hB/wFRvLEDehcxyHuumBCqKrD/DSKmC+b017Ebd99tBbS7wKBgH0p1ioADWTkrGqbQ4q7e/kEYcROEYwdcnXd5bNjMcv48izpT++G2wOacZu3/EiM5KtkXRnOWZIAjbhdiUMH0oUmiAnS85sTulEE6BMY3Y6ZznSltF681OfpnwXTFOnYuYMstCwV0T8YfLx51h0wAUyZLOCY/m+QoP1tLCAtAri5AoGAD5UxRk9RG1PhggdKkAv4nB99i4MpODVuo8BRjhRtQCurGxnUx2htlua3I0xvVWidnIVA6wj88guBfaB5cIAezPFwxKbg8ePdfnNpxxhzDFWazgT6FyaStC415HRjxfVyrXuGlipvL8Wo3YSgD6ru8FC+MNX+lA1TmAyv4bSkHWUCgYAGRhj6RjLGKs1nY5DIWe+M0hg90FwHNxiIbDgTkdPJ/gkqHUpgOLSPjzr3FKFxiNilzMTTjlB8KK1Mv2DMYN8DYYXKrxVmYOrJkNaCjK9e/WTJ0BEmWPNm+NmTvL8dhb/G+5gGqOA9y6zy7IdQ5Y9NMQA2col7dyaniW9+lRBKBw==
  # Public certificate to verify the signature of the SAML response
  certificate: MIIDPjCCAiagAwIBAgIJAKg3FyvbFyryMA0GCSqGSIb3DQEBBQUAMB4xHDAaBgNVBAoTE1NVUkZuZXQsIENOPUlkZW5zeXMwHhcNMTYwNjA5MDczODM3WhcNMjYwNjA5MDczODM3WjAeMRwwGgYDVQQKExNTVVJGbmV0LCBDTj1JZGVuc3lzMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAu85sgd7E6hhk8LqJJIe+aUBVU6gWKGBbFz1aj5dNvfTqoTWKRK3yp2GMqcqNwDAsSScWSixsHRdCY3noMgvQW8E3l5MEjoUXN/UEciB7g7FJK6uopnCkUIzKp/dCUV5uqNTzB8/NOwhy9swgs4H77YHAaXlA2ePm2vauf0QMLAJfyi90k3YG1sk9ekyMTgcxUrRLfUKQDnz4i8I9/dtuVj+5v7/wSR1fDB8BxgYNVmF/h/2oeTUliTEo/9F0qBvpa4kvRzmz6RT/wa38E3pr68am8+5bx6M3FU+mycfmpc+CFmGFNKbTGRBtiwkIwyta55HGOxG4lKikIXvpeEu05wIDAQABo38wfTAdBgNVHQ4EFgQUg62VZtg/0Vnz7x5PM/IIU5oPYfAwTgYDVR0jBEcwRYAUg62VZtg/0Vnz7x5PM/IIU5oPYfChIqQgMB4xHDAaBgNVBAoTE1NVUkZuZXQsIENOPUlkZW5zeXOCCQCoNxcr2xcq8jAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBBQUAA4IBAQCEPnyvxcsOL1ZakINodIPNjMfSSqh9aVEW231Luaz/1ow81YfW8woIMOl2VAT7bp6BEVkYS91qdOxynVV+CKjaLLhR+zNC2mLW8whv4ZDt4arCBUWHjEUXLGhFTqE+0tofaWtUsXAWrJFOPGbq2EvLRIza2o4JSI6cIO97q2f5VrDwyNHO3QiEdTBBBbbCtx526W56IlVlxX1lRFR05q6gzmprMf0lkoX/EBq3ELtpEhd5Z2d5V59GXsgNbe+oW6BVUGSsbwk4yyQcx39338Qfl9k1WpjAXIFnRzT4npy/M5JIfg6p1kN9nygrhpoHBEhQ160h7hLjHQb6Qnbqv5Pw
  # Passphrase of the keystore
  passphrase: secret
  # ACS location
  acs_location: http://localhost:8080/saml/SSO
  # duration of metadata cache (1 day)
  validity_duration_metadata_ms: 86400000
  # value of the keyName in the KeyDescriptor
  key_name: whatever-configurable
  # the resource location of the metadata for the SP
  metadata_resource_sp: classpath:saml/eidas.proxy.sp.metadata.xml

sp:
  destination: https://tst-peps.minez.nl/PEPS/ServiceProvider
  certificate: |
    MIIHgjCCBWqgAwIBAgIUDG49FiCHQxlDjeQz95f4INk/WSQwDQYJKoZIhvcNAQELBQAwgYUxCzAJ
    BgNVBAYTAk5MMR4wHAYDVQQKDBVRdW9WYWRpcyBUcnVzdGxpbmsgQlYxKDAmBgNVBAsMH0lzc3Vp
    bmcgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkxLDAqBgNVBAMMI1F1b1ZhZGlzIENTUCAtIFBLSSBP
    dmVyaGVpZCBDQSAtIEcyMB4XDTE0MDMyNjE1MzE0MFoXDTE3MDMyNjE1MzEzN1owga0xHTAbBgNV
    BAUTFDAwMDAwMDAxMDAzMTY2OTQ2MDAwMQswCQYDVQQGEwJOTDEpMCcGA1UEChMgbWluaXN0ZXJp
    ZSB2YW4gRWNvbm9taXNjaGUgWmFrZW4xHjAcBgNVBAsTFURpZW5zdCBJQ1QgVWl0dm9lcmluZzE0
    MDIGA1UEAxMrQUNDLU5MLU1pbkVaLVBFUFMtU0FNTC1DbGllbnQtU2lnbi5taW5lei5ubDCCASIw
    DQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAOHYFPWH9OoLdwIzU4yc6PZpMI3o/RlTwPvFsn7+
    UryLNBHY4ZOtuB8GXfM30qNzYNHtrYPudrtyOnZBFqonGySjbc4tNO4QVUQqxpcs7v9SBFZeHCS6
    96As2zF/RXjlBSxzSzpK6a5zGv9FEx6vRjP/uHU+XESk0XH5TlZIdKibn5FHEcYuUFR5egbmbCci
    P7tgJgqwgXqgqFMcWTCQjHZB25bc8cccbX1lR9yzYFqnV15vwhDgH+0cnD+tyEfN6OFfyR9J98ji
    2pbJmi8fYdNX8mGeEleDVXFsgi1vTcYTw/nKg1UoqYdnCprQ+4mgbjSIlgwJvIvQxqKmVfYnQEsC
    AwEAAaOCAr4wggK6MAwGA1UdEwEB/wQCMAAwggExBgNVHSAEggEoMIIBJDCCASAGCmCEEAGHawEC
    BQQwggEQMIHXBggrBgEFBQcCAjCByhqBx1JlbGlhbmNlIG9uIHRoaXMgY2VydGlmaWNhdGUgYnkg
    YW55IHBhcnR5IGFzc3VtZXMgYWNjZXB0YW5jZSBvZiB0aGUgcmVsZXZhbnQgUXVvVmFkaXMgQ2Vy
    dGlmaWNhdGlvbiBQcmFjdGljZSBTdGF0ZW1lbnQgYW5kIG90aGVyIGRvY3VtZW50cyBpbiB0aGUg
    UXVvVmFkaXMgcmVwb3NpdG9yeSAgKGh0dHA6Ly93d3cucXVvdmFkaXNnbG9iYWwuY29tKS4wNAYI
    KwYBBQUHAgEWKGh0dHA6Ly93d3cucXVvdmFkaXNnbG9iYWwuY29tL3JlcG9zaXRvcnkwSQYDVR0R
    BEIwQKA+BgorBgEEAYI3FAIDoDAMLjIuMTYuNTI4LjEuMTAwMy4xLjMuNS4yLjEtMDAwMDAwMDEw
    MDMxNjY5NDYwMDAwcwYIKwYBBQUHAQEEZzBlMCoGCCsGAQUFBzABhh5odHRwOi8vb2NzcC5xdW92
    YWRpc2dsb2JhbC5jb20wNwYIKwYBBQUHMAKGK2h0dHA6Ly90cnVzdC5xdW92YWRpc2dsb2JhbC5j
    b20vcXZvY2FnMi5jcnQwDgYDVR0PAQH/BAQDAgeAMCkGA1UdJQQiMCAGCCsGAQUFBwMCBggrBgEF
    BQcDBAYKKwYBBAGCNxQCAjAfBgNVHSMEGDAWgBRpy39QdgCGU5V5EsFYdh8T7/JNozA6BgNVHR8E
    MzAxMC+gLaArhilodHRwOi8vY3JsLnF1b3ZhZGlzZ2xvYmFsLmNvbS9xdm9jYWcyLmNybDAdBgNV
    HQ4EFgQU2/kYM8M2zvTbNKoe/JcaMDSg8tswDQYJKoZIhvcNAQELBQADggIBAF1G1YTeuOn+VFFJ
    nQjN1couk01CdZiOrJzoBJ0FG7E3OPPgkvqfEwCM94cXiObC7/J+Obuk9XpRcBhww6SddtxTctVc
    oxReFR6jnPbHky4SVXLfHnLAc0w7gVzb0WeRtNI87ELKgmnmYlgBj2QgH4gxYszUvAKmZLHZlxNW
    9xdU9q2eK+2lGhuDQwOJv4rE4q7VC3hrhTEqT/XqFusENPWF1QiZQ5uN7MtF7lrHsrXYNApsxgWJ
    fp/TxZwj4jSbqc+PQ0Pdoe6kyrBh7QQ/pR6WgPBI25PQlBJgqZ1+EwyrBDGkwCOY/EJq0uZFtLky
    Jy+s1gatf8NUh71cb/3CDe2HwaCrwvGeDvZDCiNX48esNYIVvmCoDa6vqpyhyCLQwemh84ZU805q
    NBK5YZGoh/IqNNQ1Xe7HE6DrWLsbm/sLtjkuekTeZ1xsrgUOhU40p1m+hWAU0Kx6ReJKHeAMx9Wj
    ZkqJ4krBDUyjSddEFF5Mc6FblIndDG/mE1O+wc5+bMfADcJ2cOcOmM06IK7Yuaqfk91lLLYA92J/
    HSWX5dcgdrxph13jA8M1ImYnr7pCLnTPE2EShEokKCQ8EAf7fFhXdZHWALsFpcK/XjKup9ybvuax
    /InUZz89Y6W7KiSaqaJ8S1Y7jAK5yFkREzKq5sKL0D7HlW6bck0R2UcWfByf
  acs_url: https://localhost:8080/saml/acs
  provider_name: Surfnet-SP
  issuer: https://eidas.localhost.surfconext.nl
  qaa_level: 3
  sector: Education
  institution: SURFnet
  application: SURFConext
  country: NL
  requested_attributes:
    names: eIdentifier,givenName #,surname,inheritedFamilyName,dateOfBirth,gender,textResidenceAddress
    mandatory_values: true,true #,true,true,true,true,true
    optional_values: "," #,,,,,"

# You can skip all the key-value pairs below in the overriding application.yml on the classpath

spring:
  mvc:
    favicon:
      enabled: false
  velocity:
    check-template-location: False

# 8 hours before we time-out
session-timeout: 28800

# We disable all endpoints except health for the load-balancer and info for git information.
endpoints:
  enabled: false
  jmx:
    enabled: false
  health:
    enabled: true
  info:
    enabled: true

# used by the git plugin
info:
  build:
    artifact: "@project.artifactId@"
    version: "@project.version@"
